import AppKit
import SwiftUI

private let translations: [String: (zh: String, en: String)] = [
    "appName": ("路径同步", "PathSync"),
    "schedule": ("默认计划", "Default schedule"),
    "scheduleSubtitle": ("所有已启用路径共用这项计划；每组可单独选择同步方向。", "All enabled folders follow this schedule. Each folder has its own sync direction."),
    "folders": ("同步路径", "Folders"),
    "addFolder": ("添加路径", "Add folder"),
    "removeFolder": ("移除路径", "Remove folder"),
    "about": ("关于", "About"),
    "history": ("同步记录", "History"),
    "unnamed": ("未命名路径", "Unnamed folder"),
    "disabled": ("未启用", "Disabled"),
    "log": ("查看原始日志", "Open raw log"),
    "historyTitle": ("最近的同步", "Recent syncs"),
    "historyCount": ("共 %d 条记录 · 当前显示 %d 条", "%d records · showing %d"),
    "historyRefresh": ("刷新", "Refresh"),
    "historyFolderFilter": ("路径", "Folder"),
    "historyResultFilter": ("结果", "Result"),
    "historyAllFolders": ("全部路径", "All folders"),
    "historyAllResults": ("全部结果", "All results"),
    "historyWithChanges": ("有变更", "With changes"),
    "historyCompleted": ("已完成", "Completed"),
    "historyPreview": ("预览", "Preview"),
    "historyAttention": ("当时有问题", "Issues at the time"),
    "historyFailed": ("未完成", "Incomplete"),
    "historyInterrupted": ("记录中断", "Interrupted"),
    "historyDirection": ("同步方向", "Direction"),
    "historyResult": ("本次结果", "This run"),
    "historyUploaded": ("上传", "Uploaded"),
    "historyDownloaded": ("下载", "Downloaded"),
    "historyCopied": ("已复制", "Copied"),
    "historyKeptBoth": ("保留两份", "Kept both"),
    "historyReviews": ("待人工合并", "Awaiting review"),
    "historyReview": ("待人工合并", "Awaiting review"),
    "historyWouldKeepBoth": ("计划保留两份", "Would keep both"),
    "historyConflicts": ("冲突", "Conflicts"),
    "historyFailures": ("失败", "Failed"),
    "historyBackups": ("已备份", "Backups"),
    "historyDeleted": ("已删除", "Deleted"),
    "historyPendingDelete": ("待确认删除", "Deletion pending confirmation"),
    "historyNewest": ("按日期选择", "Chosen by date"),
    "historyBackup": ("覆盖前版本", "Previous version"),
    "historyDeleteBackup": ("删除前版本", "Deleted version"),
    "restoreBackup": ("恢复此版本", "Restore this version"),
    "backupExpired": ("备份已过期", "Backup expired"),
    "backupSideLocal": ("本地", "Local"),
    "backupSideCloud": ("云端", "Cloud"),
    "historyNoChanges": ("没有文件变更", "No file changes"),
    "historyNoSummary": ("未取得文件统计", "File counts unavailable"),
    "historyNoFileDetails": ("没有需要逐文件处理的冲突或错误。", "No per-file conflicts or errors were recorded."),
    "historyCopy": ("冲突副本：", "Conflict copy:"),
    "historyOpenLocal": ("打开本地", "Open local"),
    "historyFileActions": ("打开或定位文件", "Open or reveal file"),
    "historyRevealLocal": ("定位本地", "Reveal local"),
    "historyOpenCloud": ("打开云端", "Open cloud"),
    "historyRevealCloud": ("定位云端", "Reveal cloud"),
    "historyOpenCopy": ("打开副本", "Open copy"),
    "historyRevealCopy": ("定位副本", "Reveal copy"),
    "historyOpenBackup": ("打开覆盖前备份", "Open pre-overwrite backup"),
    "historyRevealBackup": ("定位覆盖前备份", "Reveal pre-overwrite backup"),
    "historyBackupVersion": ("覆盖前备份", "Pre-overwrite backup"),
    "historyCurrentLocal": ("当前本地文件", "Current local file"),
    "historyCurrentCloud": ("当前云端文件", "Current cloud file"),
    "historyDiff": ("LaTeX 差异与摘要", "LaTeX diff and summary"),
    "historyDiffTitle": ("LaTeX 差异", "LaTeX differences"),
    "historyDiffCurrentHint": ("备份记录比较覆盖前备份与当前文件；其他记录比较当前磁盘上的版本。", "Backup events compare the saved pre-overwrite version with the current file; other events compare current files."),
    "historyDiffTruncated": ("差异较长，界面只显示前 4000 行。", "The diff is long; only its first 4,000 lines are shown."),
    "historyCodexSummary": ("用 Codex CLI 解读", "Summarize with Codex CLI"),
    "historyCodexHint": ("点击后才会将当前差异文本交给 Codex CLI。", "The current diff is sent to Codex CLI only when clicked."),
    "historyClose": ("关闭", "Close"),
    "historyEmpty": ("还没有这几组路径的同步记录。", "No sync records for these folders yet."),
    "historyFilterEmpty": ("没有符合筛选条件的记录。", "No records match these filters."),
    "historyLogHint": ("原始日志仅用于排查问题", "Raw log for troubleshooting"),
    "historyHistoricalHint": ("记录显示当时的结果；当前冲突请查看对应路径。", "Records show the result at the time. Check each folder for current conflicts."),
    "save": ("保存设置", "Save settings"),
    "syncNow": ("立即同步", "Sync now"),
    "syncAllNow": ("同步全部路径", "Sync all folders"),
    "syncPairNow": ("同步此路径", "Sync this folder"),
    "syncAllHint": ("按各路径设定的方向执行", "Use each folder's selected direction"),
    "syncPairHint": ("按这组路径设定的方向执行", "Use this folder's selected direction"),
    "ready": ("准备就绪", "Ready"),
    "conflictsPending": ("有待合并或待处理的版本，请打开对应路径查看。", "Versions still need review. Open the affected folder."),
    "chooseFoldersHint": ("选择本地和云端文件夹，然后保存。", "Choose local and cloud folders, then save."),
    "removedHint": ("已从列表移除；保存后生效。", "Removed from the list. Save to apply."),
    "savedEnabled": ("已保存，后台同步已启用。", "Saved. Scheduled sync is on."),
    "savedDisabled": ("已保存，后台同步已关闭。", "Saved. Scheduled sync is off."),
    "syncingAll": ("正在同步所有已启用路径…", "Syncing all enabled folders…"),
    "syncingPair": ("正在同步所选路径…", "Syncing the selected folder…"),
    "scanProgress": ("%@：扫描%@目录，已检查 %@ 个文件夹、%@ 个文件", "%@: scanning %@, %@ folders and %@ files checked"),
    "processProgress": ("%@：正在核对文件 %@/%@", "%@: comparing files %@/%@"),
    "prefetchProgress": ("%@：正在读取云端文件 %@/%@", "%@: reading cloud files %@/%@"),
    "fileProgress": ("%@：正在核验 %@", "%@: checking %@"),
    "waitingForCloud": ("%@：等待 OneDrive 读取 %@（已等 %@ 秒）", "%@: waiting for OneDrive to read %@ (%@ seconds)"),
    "doneAll": ("所有已启用路径同步完成。", "All enabled folders are synced."),
    "donePair": ("所选路径同步完成。", "Selected folder is synced."),
    "keptBothResult": ("同步完成，已保留 %d 组冲突的两个版本。", "Sync complete. Both versions were kept for %d conflict(s)."),
    "reviewsRemain": ("其余文件已同步；仍有 %d 个版本待人工合并或确认。", "Other files synced; %d version(s) still need review."),
    "error": ("操作失败", "Operation failed"),
    "resolving": ("正在处理冲突…", "Resolving conflict…"),
    "resolved": ("冲突已处理；两侧原件已备份。", "Conflict resolved. Both originals were backed up."),
    "preservedReview": ("两个版本已保留，仍待人工合并或确认。", "Both versions are safe; manual review is still needed."),
    "reviewAcknowledged": ("已确认处理完成；保留的副本未删除。", "Review confirmed. The preserved copy was not deleted."),
    "newestResolved": ("已采用当前修改日期较新的版本；如有覆盖，旧版本已备份。", "The version with the later current modification date was kept; any replaced versions were backed up."),
    "restoringBackup": ("正在恢复备份…", "Restoring backup…"),
    "backupRestored": ("版本已恢复；恢复前的文件也已备份。", "Version restored; the replaced file was backed up."),
    "daily": ("每天固定时间", "Every day at a time"),
    "interval": ("固定间隔", "At an interval"),
    "runMode": ("运行方式", "Run mode"),
    "runTime": ("同步时间", "Sync time"),
    "intervalHours": ("间隔", "Interval"),
    "hours": ("小时", "hours"),
    "days": ("天", "days"),
    "atLeastSix": ("可设为 6 至 168 小时。间隔从任务安装后开始计算。", "Set 6–168 hours. The interval starts when the scheduled task is installed."),
    "dailyHint": ("按这台 Mac 的本地时间运行。", "Runs at this Mac’s local time."),
    "background": ("启用后台同步", "Enable scheduled sync"),
    "backgroundHint": ("设置保存在本机，由 macOS 在你登录期间定时运行。", "Settings stay on this Mac. macOS runs the task while you are signed in."),
    "notifications": ("同步通知", "Sync notifications"),
    "notificationsOff": ("关闭", "Off"),
    "notificationsIssues": ("冲突或失败时", "On conflicts or failures"),
    "notificationsAll": ("每次同步后", "After every sync"),
    "notificationHint": ("通知默认关闭；选择开启时由 macOS 请求权限。", "Notifications are off by default. macOS asks for permission when you enable them."),
    "notificationDenied": ("未获得通知权限；通知保持关闭。", "Notification permission was not granted; notifications remain off."),
    "notificationIssueTitle": ("路径同步需要注意", "PathSync needs attention"),
    "notificationIssueBody": ("同步遇到冲突或失败，请打开应用查看。", "A sync found a conflict or error. Open the app for details."),
    "notificationDoneTitle": ("路径同步已完成", "PathSync finished"),
    "notificationDoneBody": ("已按设置同步路径。", "Folders were synced using your settings."),
    "menubarOpen": ("打开路径同步", "Open PathSync"),
    "menubarOpenHistory": ("查看同步记录", "View sync history"),
    "menubarQuit": ("退出路径同步", "Quit PathSync"),
    "menubarPending": ("%d 个版本待处理", "%d version(s) need review"),
    "menubarNoPairs": ("尚无已启用路径", "No enabled folders"),
    "filterTitle": ("文件过滤", "File filtering"),
    "pairFilters": ("此路径的文件范围", "Files in this folder pair"),
    "syncCodexFiles": ("同步 Codex 项目文件", "Sync Codex project files"),
    "syncClaudeFiles": ("同步 Claude Code 项目文件", "Sync Claude Code project files"),
    "syncTemporaryFiles": ("同步 tmp 等临时文件", "Sync tmp and temporary files"),
    "pairFiltersHint": ("Codex 包括 AGENTS.md、.codex/、.agents/；Claude Code 包括 CLAUDE.md、.claude/、.mcp.json。本机专用的 .claude/settings.local.json 始终跳过。tmp、temp、.tmp 及临时后缀默认跳过。更改过滤规则不会删除已同步的文件。", "Codex includes AGENTS.md, .codex/, and .agents/. Claude Code includes CLAUDE.md, .claude/, and .mcp.json. Machine-local .claude/settings.local.json is always skipped. tmp, temp, .tmp, and temporary suffixes are skipped by default. Changing filters never deletes previously synced files."),
    "latex": ("跳过 LaTeX 中间文件", "Skip LaTeX build files"),
    "conflictHandling": ("冲突处理", "Conflict handling"),
    "autoKeepBoth": ("自动保留两份", "Keep both automatically"),
    "askForConflicts": ("暂停并手动选择", "Pause for a decision"),
    "keepNewest": ("保留修改日期较新的版本", "Keep version with newer modification date"),
    "chooseNewest": ("采用当前较新版本", "Use newer current version"),
    "backupRetention": ("备份保留", "Keep backups for"),
    "backupHint": ("删除与编辑一样按上次共同状态判断；覆盖和删除前先备份，到期后在后续同步中清理。", "Deletion and edits use the same last common state. Backups are made before overwrite or deletion and cleaned after expiry on a later sync."),
    "conflictPolicyHint": ("默认自动保留两个版本并标记待合并；处理前备份原件。", "By default, both versions are kept and marked for review; originals are backed up first."),
    "filterHint": ("也会跳过虚拟环境与缓存。", "Virtual environments and caches are also skipped."),
    "runAll": ("现在同步全部路径", "Sync all folders now"),
    "pairSubtitle": ("本地工作目录与已挂载的云端目录。", "A local working folder and a mounted cloud folder."),
    "pairEnabled": ("启用这组路径", "Enable this folder pair"),
    "name": ("名称", "Name"),
    "namePlaceholder": ("路径名称", "Folder name"),
    "local": ("本地", "Local"),
    "cloud": ("云端", "Cloud"),
    "chooseFolder": ("选择文件夹", "Choose folder"),
    "browse": ("选择…", "Choose…"),
    "direction": ("定时方向", "Scheduled direction"),
    "merge": ("双向合并", "Two-way merge"),
    "upload": ("本地 → 云端", "Local → cloud"),
    "download": ("云端 → 本地", "Cloud → local"),
    "directionHintAuto": ("发现不同版本时自动保留两份，并持续提示人工合并。", "Differing versions are kept automatically and remain marked for review."),
    "directionHintAsk": ("发现不同版本时暂停该文件，并在下方列出待处理冲突。", "Differing versions pause that file and appear below for review."),
    "directionHintNewest": ("只有两侧相对共同版本都更新时才按修改日期选择；日期相同则暂停。", "Only if both sides changed from the common version is modification date used; ties pause."),
    "conflicts": ("待处理冲突", "Pending conflicts"),
    "refreshConflicts": ("刷新冲突列表", "Refresh conflicts"),
    "noConflicts": ("当前没有待处理版本。", "No versions need review."),
    "reviewOutstanding": ("两个版本已保留，内容尚未确认合并。", "Both versions are preserved; their contents have not been confirmed as merged."),
    "reviewCopy": ("保留的另一版本：", "Preserved other version:"),
    "viewMainFile": ("查看主文件", "Show main file"),
    "viewReviewCopy": ("查看另一版本", "Show other version"),
    "confirmReviewed": ("确认已处理", "Mark reviewed"),
    "viewLocal": ("查看本地", "Show local"),
    "viewCloud": ("查看云端", "Show cloud"),
    "resolve": ("选择版本", "Choose version"),
    "useLocal": ("采用本地版本", "Use local version"),
    "useCloud": ("采用云端版本", "Use cloud version"),
    "keepDeletion": ("保留删除", "Keep deletion"),
    "deleteEditConflict": ("一侧删除、另一侧编辑；请选择保留文件或删除。", "One side deleted and the other edited; choose whether to keep the file or deletion."),
    "directoryConflict": ("一侧删除了目录，另一侧修改了内部文件。整个目录已暂停同步。请检查两侧并手动使其一致，或都删除，再刷新冲突列表。", "One side deleted this folder while the other changed a file inside it. Sync is paused for the whole folder. Make both folders agree, or delete both, then refresh conflicts."),
    "childBlockedByTree": ("上级目录仍有冲突；请先整体处理该目录。", "The parent folder has a conflict. Resolve the folder as a whole first."),
    "keepBoth": ("保留两份（仍待合并）", "Keep both (review still needed)"),
    "conflictHint": ("保留两份后，请检查另一版本并自行合并，或确认无需合并，再点“确认已处理”。其他文件会照常同步；副本和备份不会删除。", "After preserving both versions, inspect and merge the other version or decide to keep them separate, then mark it reviewed. Other files continue syncing; copies and backups remain."),
    "usingSchedule": ("使用默认计划", "Uses default schedule"),
    "editSchedule": ("编辑计划", "Edit schedule"),
    "runNow": ("立即执行", "Run now"),
    "empty": ("还没有路径。点击左侧的“添加路径”开始。", "No folders yet. Use Add folder in the sidebar."),
    "language": ("界面语言", "Interface language"),
    "systemLanguage": ("跟随系统", "Follow system"),
    "chinese": ("简体中文", "Simplified Chinese"),
    "english": ("English", "English"),
    "aboutSubtitle": ("简单、可检查的本地文件夹同步。", "Simple, inspectable local folder sync."),
    "version": ("版本", "Version"),
    "source": ("源代码与发布版本", "Source code and releases"),
    "author": ("作者", "Author"),
    "scheduleSummaryDaily": ("每天", "Every day at"),
    "scheduleSummaryInterval": ("每隔", "Every"),
    "manual": ("手动", "Manual"),
    "overview": ("概览", "Overview"),
    "settings": ("设置", "Settings"),
    "general": ("通用", "General"),
    "launchAtLogin": ("登录后启动", "Launch at login"),
    "launchAtLoginApproval": ("需要在系统设置的登录项中批准", "Approve this app in System Settings > Login Items"),
    "conflictsAndBackups": ("冲突与备份", "Conflicts and backups"),
    "directionSection": ("同步方式", "Sync method"),
    "enabledShort": ("启用", "Enabled"),
    "syncing": ("正在同步…", "Syncing…"),
    "statusReady": ("同步已就绪", "Ready to sync"),
    "lastSync": ("上次同步", "Last sync"),
    "never": ("尚无", "never"),
    "nextRun": ("下次", "Next"),
    "scheduleOff": ("后台同步已关闭", "Scheduled sync is off"),
    "backgroundOn": ("后台同步已开启", "Scheduled sync is on"),
    "pairOK": ("正常", "OK"),
    "pairPending": ("%d 项待处理", "%d pending"),
    "pairLastFailed": ("上次未完成", "Last run incomplete"),
    "pairNotConfigured": ("未选择文件夹", "Folders not set"),
    "folderNotChosen": ("未选择", "Not chosen"),
    "revealInFinder": ("在访达中打开", "Open in Finder"),
    "syncOnceIn": ("按其他方向同步一次", "Sync once in another direction"),
    "removeConfirm": ("移除“%@”？", "Remove “%@”?"),
    "removeConfirmHint": ("只从列表中移除，不会删除任何文件；保存后生效。", "This only removes it from the list. No files are deleted. Save to apply."),
    "unsaved": ("有未保存的更改", "Unsaved changes"),
    "updates": ("软件更新", "Software update"),
    "updateBadge": ("新", "New"),
    "checkForUpdates": ("检查更新…", "Check for Updates…"),
    "checkForUpdatesButton": ("检查更新", "Check now"),
    "autoCheckUpdates": ("自动检查更新", "Check for updates automatically"),
    "autoInstallUpdates": ("自动安装已签名的更新", "Install signed updates automatically"),
    "autoCheckHint": ("每天最多向 GitHub 查询一次最新发布版本，不发送文件名、路径或其他个人数据。", "Asks GitHub for the latest release at most once a day. No file names, paths, or other personal data are sent."),
    "updateNotChecked": ("尚未检查更新", "Not checked yet"),
    "updateChecking": ("正在检查更新…", "Checking for updates…"),
    "updateUpToDate": ("已是最新发布版本（%@）", "Latest released version installed (%@)"),
    "updateAheadOfRelease": ("本机版本 %@ 尚未发布；最新发布版为 %@", "Local build %@ is ahead of the latest release %@"),
    "updateScopeHint": ("检查对象是 GitHub Release 安装包；main 分支上的未发布提交不会触发应用更新。", "Checks GitHub Release packages. Unreleased commits on main do not trigger an app update."),
    "updateFailed": ("无法检查更新，请检查网络后重试。", "Couldn’t check for updates. Check your connection and try again."),
    "updateAvailable": ("新版本 %@ 可用", "Version %@ is available"),
    "updateLastChecked": ("上次检查：", "Last checked:"),
    "justNow": ("刚刚", "just now"),
    "updateDownload": ("下载", "Download"),
    "updateInstall": ("安装并重新打开", "Install and relaunch"),
    "updateDownloading": ("正在下载安装包…", "Downloading update…"),
    "updateVerifying": ("正在校验签名与应用…", "Verifying signature and app…"),
    "updateReplacing": ("正在替换并重新打开应用…", "Replacing and relaunching app…"),
    "updateDetails": ("详情", "Details"),
    "updateReleaseNotes": ("更新说明", "Release notes"),
    "updateInstallHint": ("安装前会校验发布签名；应用退出后替换并重新打开。同步运行中或设置未保存时暂不安装。", "The release signature is verified before installation. The app replaces itself after quitting, then relaunches. Installation waits while syncing or settings are unsaved."),
    "updateManualHint": ("这个版本没有自动安装所需的签名；请下载并手动替换应用。", "This release lacks an auto-install signature. Download it and replace the app manually."),
    "menubarUpdate": ("新版本 %@ 可用…", "Version %@ available…"),
    "cloudConfig": ("iCloud 配置", "iCloud configuration"),
    "localRoot": ("本机工作根目录", "Local working root"),
    "chooseLocalRoot": ("选择…", "Choose…"),
    "cloudPreviewTitle": ("预览配置导入", "Review configuration import"),
    "cloudPreviewHint": ("导入时会在本机工作根目录创建下面列出的空文件夹；不会复制或删除已有文件。新增或路径改变的组保持关闭，检查后再保存。", "Import creates the empty local folders listed below under this Mac's working root. It does not copy or delete existing files. New or rebound folders stay disabled until reviewed and saved."),
    "cloudNoChanges": ("与本机当前规则一致；可记录这个远端版本为已导入。", "Rules match this Mac. You can record this remote revision as imported."),
    "cloudPreservedLocal": ("远端未包含的路径组仍保留在本机", "Folders absent remotely remain on this Mac"),
    "cloudRulesConflict": ("本机和这台设备在上次导入后都修改了共享规则。请检查差异，再选择采用远端规则或保留本机。", "Both devices changed shared rules since the last import. Review the changes before using remote rules or keeping local rules."),
    "cloudLocalEdits": ("本机规则已修改；导入会替换这些更改。请先检查下列差异。", "Local rules changed; importing will replace those edits. Review the changes below."),
    "enabled": ("开启", "On"),
    "scheduledDirection": ("定时方向", "Scheduled direction"),
    "cloudUseRemoteRules": ("采用远端规则", "Use remote rules"),
    "cloudUnset": ("未设置", "Not set"),
    "cloudPairDisabled": ("此路径暂不参与定时同步", "This folder will not sync on schedule yet"),
    "cloudMissingFolders": ("本机尚不存在的目录", "Folders missing on this Mac"),
    "cloudFoldersToCreate": ("导入时创建的本地空目录", "Empty local folders created on import"),
    "cloudRevisionApplied": ("此版本已导入", "This revision was imported"),
    "cloudRevisionNew": ("有新版本", "New revision available"),
    "cloudRevisionNever": ("尚未导入", "Not imported"),
    "cloudThisDevice": ("这台 Mac", "This Mac"),
    "cloudTransfer_uploaded": ("iCloud 已报告上传完成", "iCloud reports upload complete"),
    "cloudTransfer_uploading": ("正在上传", "Uploading"),
    "cloudTransfer_pending": ("等待上传", "Upload pending"),
    "cloudTransfer_error": ("上传出错", "Upload error"),
    "cloudTransfer_missing": ("尚未写入配置", "Configuration not written"),
    "cloudTransfer_unknown": ("系统未提供传输状态", "Transfer status unavailable"),
    "cloudPeerImported": ("对方已报告导入本机当前配置", "Peer reports importing this Mac's current revision"),
    "cloudPeerUnconfirmed": ("对方尚未报告导入本机当前配置", "Peer has not reported importing this Mac's current revision"),
    "configRollback": ("配置回退", "Configuration rollback"),
    "configNoBackups": ("保存配置后，旧版本会显示在这里。", "Previous versions appear here after saving changes."),
    "configLoadBackup": ("载入预览", "Load for review"),
    "configRollbackHint": ("载入旧版只改变当前编辑内容；检查后点击“保存设置”才会生效。", "Loading a previous version changes only the current draft. Review it and choose Save settings to apply."),
    "cancel": ("取消", "Cancel"),
    "cloudConfigEnable": ("通过 iCloud Drive 共享配置", "Share configuration through iCloud Drive"),
    "cloudConfigHint": ("保存后发布路径组名称、相对路径、同步方向、计划和规则。不会上传本机绝对路径、启用状态、同步记录或文件内容。另一台 Mac 可选择导入。", "Saving publishes folder names, relative paths, directions, schedule, and rules. Absolute paths, enabled state, history, and file contents stay on this Mac. Import on another Mac when ready."),
    "oneDriveRoot": ("本机 OneDrive 根目录", "OneDrive root on this Mac"),
    "chooseOneDriveRoot": ("选择…", "Choose…"),
    "oneDriveRootHint": ("本机工作根目录默认是“文稿/Documents”；导入时自动组合对应路径。旧配置缺少本地相对路径时，从 OneDrive 相对路径推导。", "The local working root defaults to Documents. Import rebuilds matching paths; older profiles without local relative paths use their OneDrive relative paths."),
    "cloudProfiles": ("其他 Mac 的配置", "Configurations from other Macs"),
    "cloudRefresh": ("刷新列表", "Refresh list"),
    "cloudImport": ("导入规则", "Import rules"),
    "cloudNone": ("还没有其他 Mac 发布的配置。", "No other Mac has published a configuration yet."),
    "cloudImportHint": ("导入后请检查路径并保存；新增或路径变化的组会关闭定时同步。远端删掉的组不会自动删除本机配置。", "Review paths and save after import. New or rebound folders stay disabled. Remote removals do not delete local folders."),
    "cloudImported": ("已导入规则；请检查路径并保存。", "Rules imported. Review paths and save."),
    "cloudNoRelative": ("%d 组云端目录不在所选 OneDrive 根目录内，无法跨 Mac 自动定位。", "%d cloud folders are outside the selected OneDrive root and cannot be located automatically on another Mac."),
    "cloudPublished": ("已写入本机 iCloud Drive；上传状态由系统管理", "Written to local iCloud Drive; upload is managed by the system"),
    "cloudLocalOnly": ("尚未发布", "Not published yet"),
]

func usesEnglish(_ language: String) -> Bool {
    language == "en" || (language == "system" && !(Locale.preferredLanguages.first ?? "zh").hasPrefix("zh"))
}

func uiText(_ key: String, language: String) -> String {
    guard let value = translations[key] else { return key }
    return usesEnglish(language) ? value.en : value.zh
}

func uiError(_ error: Error, language: String) -> String {
    guard usesEnglish(language) else { return error.localizedDescription }
    let value = error as NSError
    guard value.domain == "com.ensom.ResearchSync" else { return "The operation failed. Check History for details." }
    switch value.code {
    case 1: return "Choose both local and cloud folders for this pair."
    case 2: return "The local folder does not exist. Check its path."
    case 3: return "The cloud folder does not exist. Check its path."
    case 4: return "A folder pair cannot use the same directory or nested directories."
    case 6: return "Another sync is already running."
    case 7: return "There are no folders to sync."
    case 8: return "Some folders need attention. Review pending conflicts or History."
    case 9: return "Enable at least one folder before turning on scheduled sync."
    case 10: return "The folder paths no longer match their conflict records. Check this pair's paths."
    case 12: return "The conflict could not be resolved. Sync again if a file changed, then check History."
    default: return "The operation did not complete. Check History for details."
    }
}
