import AppKit
import SwiftUI

private let translations: [String: (zh: String, en: String)] = [
    "appName": ("路径同步", "PathSync"),
    "schedule": ("默认计划", "Default schedule"),
    "scheduleSubtitle": ("所有已启用路径共用这项计划；每组可单独选择同步方向。", "All enabled folders follow this schedule. Each folder has its own sync direction."),
    "folders": ("同步路径", "Folders"),
    "addFolder": ("添加路径", "Add folder"),
    "removeFolder": ("移除路径", "Remove folder"),
    "about": ("关于", "About"),
    "history": ("同步记录", "History"),
    "unnamed": ("未命名路径", "Unnamed folder"),
    "disabled": ("未启用", "Disabled"),
    "log": ("查看原始日志", "Open raw log"),
    "historyTitle": ("最近的同步", "Recent syncs"),
    "historyCount": ("共 %d 条记录 · 当前显示 %d 条", "%d records · showing %d"),
    "historyRefresh": ("刷新", "Refresh"),
    "historyFolderFilter": ("路径", "Folder"),
    "historyResultFilter": ("结果", "Result"),
    "historyAllFolders": ("全部路径", "All folders"),
    "historyAllResults": ("全部结果", "All results"),
    "historyWithChanges": ("有变更", "With changes"),
    "historyCompleted": ("已完成", "Completed"),
    "historyPreview": ("预览", "Preview"),
    "historyAttention": ("当时有问题", "Issues at the time"),
    "historyFailed": ("未完成", "Incomplete"),
    "historyInterrupted": ("记录中断", "Interrupted"),
    "historyDirection": ("同步方向", "Direction"),
    "historyResult": ("本次结果", "This run"),
    "historyUploaded": ("上传", "Uploaded"),
    "historyDownloaded": ("下载", "Downloaded"),
    "historyCopied": ("已复制", "Copied"),
    "historyKeptBoth": ("保留两份", "Kept both"),
    "historyReviews": ("待人工合并", "Awaiting review"),
    "historyReview": ("待人工合并", "Awaiting review"),
    "historyWouldKeepBoth": ("计划保留两份", "Would keep both"),
    "historyConflicts": ("冲突", "Conflicts"),
    "historyFailures": ("失败", "Failed"),
    "historyBackups": ("已备份", "Backups"),
    "historyDeleted": ("已删除", "Deleted"),
    "historyPendingDelete": ("待确认删除", "Deletion pending confirmation"),
    "historyNewest": ("按日期选择", "Chosen by date"),
    "historyBackup": ("覆盖前版本", "Previous version"),
    "historyDeleteBackup": ("删除前版本", "Deleted version"),
    "restoreBackup": ("恢复此版本", "Restore this version"),
    "backupExpired": ("备份已过期", "Backup expired"),
    "backupSideLocal": ("本地", "Local"),
    "backupSideCloud": ("云端", "Cloud"),
    "historyNoChanges": ("没有文件变更", "No file changes"),
    "historyNoSummary": ("未取得文件统计", "File counts unavailable"),
    "historyNoFileDetails": ("没有需要逐文件处理的冲突或错误。", "No per-file conflicts or errors were recorded."),
    "historyCopy": ("冲突副本：", "Conflict copy:"),
    "historyEmpty": ("还没有这几组路径的同步记录。", "No sync records for these folders yet."),
    "historyFilterEmpty": ("没有符合筛选条件的记录。", "No records match these filters."),
    "historyLogHint": ("原始日志仅用于排查问题", "Raw log for troubleshooting"),
    "historyHistoricalHint": ("记录显示当时的结果；当前冲突请查看对应路径。", "Records show the result at the time. Check each folder for current conflicts."),
    "save": ("保存设置", "Save settings"),
    "syncNow": ("立即同步", "Sync now"),
    "syncAllNow": ("同步全部路径", "Sync all folders"),
    "syncPairNow": ("同步此路径", "Sync this folder"),
    "syncAllHint": ("按各路径设定的方向执行", "Use each folder's selected direction"),
    "syncPairHint": ("按这组路径设定的方向执行", "Use this folder's selected direction"),
    "ready": ("准备就绪", "Ready"),
    "conflictsPending": ("有待合并或待处理的版本，请打开对应路径查看。", "Versions still need review. Open the affected folder."),
    "chooseFoldersHint": ("选择本地和云端文件夹，然后保存。", "Choose local and cloud folders, then save."),
    "removedHint": ("已从列表移除；保存后生效。", "Removed from the list. Save to apply."),
    "savedEnabled": ("已保存，后台同步已启用。", "Saved. Scheduled sync is on."),
    "savedDisabled": ("已保存，后台同步已关闭。", "Saved. Scheduled sync is off."),
    "syncingAll": ("正在同步所有已启用路径…", "Syncing all enabled folders…"),
    "syncingPair": ("正在同步所选路径…", "Syncing the selected folder…"),
    "doneAll": ("所有已启用路径同步完成。", "All enabled folders are synced."),
    "donePair": ("所选路径同步完成。", "Selected folder is synced."),
    "keptBothResult": ("同步完成，已保留 %d 组冲突的两个版本。", "Sync complete. Both versions were kept for %d conflict(s)."),
    "reviewsRemain": ("其余文件已同步；仍有 %d 个版本待人工合并或确认。", "Other files synced; %d version(s) still need review."),
    "error": ("操作失败", "Operation failed"),
    "resolving": ("正在处理冲突…", "Resolving conflict…"),
    "resolved": ("冲突已处理；两侧原件已备份。", "Conflict resolved. Both originals were backed up."),
    "preservedReview": ("两个版本已保留，仍待人工合并或确认。", "Both versions are safe; manual review is still needed."),
    "reviewAcknowledged": ("已确认处理完成；保留的副本未删除。", "Review confirmed. The preserved copy was not deleted."),
    "newestResolved": ("已采用原始修改日期较新的版本；覆盖前版本已备份。", "The version with the later original modification date was kept; replaced versions were backed up."),
    "restoringBackup": ("正在恢复备份…", "Restoring backup…"),
    "backupRestored": ("版本已恢复；恢复前的文件也已备份。", "Version restored; the replaced file was backed up."),
    "daily": ("每天固定时间", "Every day at a time"),
    "interval": ("固定间隔", "At an interval"),
    "runMode": ("运行方式", "Run mode"),
    "runTime": ("同步时间", "Sync time"),
    "intervalHours": ("间隔", "Interval"),
    "hours": ("小时", "hours"),
    "days": ("天", "days"),
    "atLeastSix": ("可设为 6 至 168 小时。间隔从任务安装后开始计算。", "Set 6–168 hours. The interval starts when the scheduled task is installed."),
    "dailyHint": ("按这台 Mac 的本地时间运行。", "Runs at this Mac’s local time."),
    "background": ("启用后台同步", "Enable scheduled sync"),
    "backgroundHint": ("设置保存在本机，由 macOS 在你登录期间定时运行。", "Settings stay on this Mac. macOS runs the task while you are signed in."),
    "filterTitle": ("文件过滤", "File filtering"),
    "latex": ("跳过 LaTeX 中间文件", "Skip LaTeX build files"),
    "conflictHandling": ("冲突处理", "Conflict handling"),
    "autoKeepBoth": ("自动保留两份", "Keep both automatically"),
    "askForConflicts": ("暂停并手动选择", "Pause for a decision"),
    "keepNewest": ("保留修改日期较新的版本", "Keep version with newer modification date"),
    "chooseNewest": ("采用日期较新版本", "Use newer dated version"),
    "propagateDeletions": ("传播单侧删除", "Propagate one-sided deletions"),
    "backupRetention": ("备份保留", "Keep backups for"),
    "backupHint": ("覆盖和删除前先备份；到期后在后续同步中清理。删除传播默认关闭。", "Back up before overwrite or deletion; expired backups are cleaned on a later sync. Deletion propagation is off by default."),
    "conflictPolicyHint": ("默认自动保留两个版本并标记待合并；处理前备份原件。", "By default, both versions are kept and marked for review; originals are backed up first."),
    "filterHint": ("也会跳过虚拟环境与缓存。", "Virtual environments and caches are also skipped."),
    "runAll": ("现在同步全部路径", "Sync all folders now"),
    "pairSubtitle": ("本地工作目录与已挂载的云端目录。", "A local working folder and a mounted cloud folder."),
    "pairEnabled": ("启用这组路径", "Enable this folder pair"),
    "name": ("名称", "Name"),
    "namePlaceholder": ("例如：论文项目", "For example: Paper project"),
    "local": ("本地", "Local"),
    "cloud": ("云端", "Cloud"),
    "chooseFolder": ("选择文件夹", "Choose folder"),
    "browse": ("选择…", "Choose…"),
    "direction": ("定时方向", "Scheduled direction"),
    "merge": ("双向合并", "Two-way merge"),
    "upload": ("本地 → 云端", "Local → cloud"),
    "download": ("云端 → 本地", "Cloud → local"),
    "directionHintAuto": ("发现不同版本时自动保留两份，并持续提示人工合并。", "Differing versions are kept automatically and remain marked for review."),
    "directionHintAsk": ("发现不同版本时暂停该文件，并在下方列出待处理冲突。", "Differing versions pause that file and appear below for review."),
    "directionHintNewest": ("只有两侧相对共同版本都更新时才按修改日期选择；日期相同则暂停。", "Only if both sides changed from the common version is modification date used; ties pause."),
    "conflicts": ("待处理冲突", "Pending conflicts"),
    "refreshConflicts": ("刷新冲突列表", "Refresh conflicts"),
    "noConflicts": ("当前没有待处理版本。", "No versions need review."),
    "reviewOutstanding": ("两个版本已保留，内容尚未确认合并。", "Both versions are preserved; their contents have not been confirmed as merged."),
    "reviewCopy": ("保留的另一版本：", "Preserved other version:"),
    "viewMainFile": ("查看主文件", "Show main file"),
    "viewReviewCopy": ("查看另一版本", "Show other version"),
    "confirmReviewed": ("确认已处理", "Mark reviewed"),
    "viewLocal": ("查看本地", "Show local"),
    "viewCloud": ("查看云端", "Show cloud"),
    "resolve": ("选择版本", "Choose version"),
    "useLocal": ("采用本地版本", "Use local version"),
    "useCloud": ("采用云端版本", "Use cloud version"),
    "keepDeletion": ("保留删除", "Keep deletion"),
    "deleteEditConflict": ("一侧删除、另一侧编辑；请选择保留文件或删除。", "One side deleted and the other edited; choose whether to keep the file or deletion."),
    "directoryConflict": ("一侧删除了目录，另一侧修改了内部文件。整个目录已暂停同步。请检查两侧并手动使其一致，或都删除，再刷新冲突列表。", "One side deleted this folder while the other changed a file inside it. Sync is paused for the whole folder. Make both folders agree, or delete both, then refresh conflicts."),
    "childBlockedByTree": ("上级目录仍有冲突；请先整体处理该目录。", "The parent folder has a conflict. Resolve the folder as a whole first."),
    "keepBoth": ("保留两份（仍待合并）", "Keep both (review still needed)"),
    "conflictHint": ("保留两份后，请检查另一版本并自行合并，或确认无需合并，再点“确认已处理”。其他文件会照常同步；副本和备份不会删除。", "After preserving both versions, inspect and merge the other version or decide to keep them separate, then mark it reviewed. Other files continue syncing; copies and backups remain."),
    "usingSchedule": ("使用默认计划", "Uses default schedule"),
    "editSchedule": ("编辑计划", "Edit schedule"),
    "runNow": ("立即执行", "Run now"),
    "empty": ("还没有路径。点击左侧的“添加路径”开始。", "No folders yet. Use Add folder in the sidebar."),
    "language": ("界面语言", "Interface language"),
    "systemLanguage": ("跟随系统", "Follow system"),
    "chinese": ("简体中文", "Simplified Chinese"),
    "english": ("English", "English"),
    "aboutSubtitle": ("简单、可检查的本地文件夹同步。", "Simple, inspectable local folder sync."),
    "version": ("版本", "Version"),
    "source": ("源代码与发布版本", "Source code and releases"),
    "author": ("作者", "Author"),
    "scheduleSummaryDaily": ("每天", "Every day at"),
    "scheduleSummaryInterval": ("每隔", "Every"),
    "manual": ("手动", "Manual"),
]

func usesEnglish(_ language: String) -> Bool {
    language == "en" || (language == "system" && !(Locale.preferredLanguages.first ?? "zh").hasPrefix("zh"))
}

func uiText(_ key: String, language: String) -> String {
    guard let value = translations[key] else { return key }
    return usesEnglish(language) ? value.en : value.zh
}

func uiError(_ error: Error, language: String) -> String {
    guard usesEnglish(language) else { return error.localizedDescription }
    let value = error as NSError
    guard value.domain == "com.ensom.ResearchSync" else { return "The operation failed. Check History for details." }
    switch value.code {
    case 1: return "Choose both local and cloud folders for this pair."
    case 2: return "The local folder does not exist. Check its path."
    case 3: return "The cloud folder does not exist. Check its path."
    case 4: return "A folder pair cannot use the same directory or nested directories."
    case 6: return "Another sync is already running."
    case 7: return "There are no folders to sync."
    case 8: return "Some folders need attention. Review pending conflicts or History."
    case 9: return "Enable at least one folder before turning on scheduled sync."
    case 10: return "The folder paths no longer match their conflict records. Check this pair's paths."
    case 12: return "The conflict could not be resolved. Sync again if a file changed, then check History."
    default: return "The operation did not complete. Check History for details."
    }
}
